// BlueprintGeneratedClass B_LackLuster_FunctionLibrary.B_LackLuster_FunctionLibrary_C
// Size: 0x28 (Inherited: 0x28)
struct UB_LackLuster_FunctionLibrary_C : UBlueprintFunctionLibrary {

	void ExecuteOwnerTypeFunctionality_PostChrome_Vehicle(struct AActor* Actor, struct UObject* __WorldContext); // Function B_LackLuster_FunctionLibrary.B_LackLuster_FunctionLibrary_C.ExecuteOwnerTypeFunctionality_PostChrome_Vehicle // (Static|Public|BlueprintCallable|BlueprintEvent) // @ game+0xdef49c
	void CleanupOwnerTypeSpecificFunctionality_Container(struct AActor* Actor, struct UObject* __WorldContext); // Function B_LackLuster_FunctionLibrary.B_LackLuster_FunctionLibrary_C.CleanupOwnerTypeSpecificFunctionality_Container // (Static|Public|BlueprintCallable|BlueprintEvent) // @ game+0xdef49c
	void CleanupOwnerTypeSpecificFunctionality(struct AActor* Actor, enum class B_Lackluster_ActorTypes ActorType, struct UObject* __WorldContext); // Function B_LackLuster_FunctionLibrary.B_LackLuster_FunctionLibrary_C.CleanupOwnerTypeSpecificFunctionality // (Static|Public|BlueprintCallable|BlueprintEvent) // @ game+0xdef49c
	void NeedsToSaveMaterialsAndTypes(struct AActor* Actor, enum class B_Lackluster_ActorTypes ActorType, struct UObject* __WorldContext, bool& Result); // Function B_LackLuster_FunctionLibrary.B_LackLuster_FunctionLibrary_C.NeedsToSaveMaterialsAndTypes // (Static|Public|HasOutParms|BlueprintCallable|BlueprintEvent|BlueprintPure) // @ game+0xdef49c
	void StopBuildingAudio(struct ABuildingActor* BuildingActor, struct UObject* __WorldContext); // Function B_LackLuster_FunctionLibrary.B_LackLuster_FunctionLibrary_C.StopBuildingAudio // (Static|Public|HasDefaults|BlueprintCallable|BlueprintEvent) // @ game+0xdef49c
	void AreWeOverridingAudio(struct AActor* Actor, struct UObject* __WorldContext, bool& Result); // Function B_LackLuster_FunctionLibrary.B_LackLuster_FunctionLibrary_C.AreWeOverridingAudio // (Static|Public|HasOutParms|BlueprintCallable|BlueprintEvent|BlueprintPure) // @ game+0xdef49c
	void Actor Support Chrome Sound Component(struct AActor* Actor, struct UObject* __WorldContext, bool& Result); // Function B_LackLuster_FunctionLibrary.B_LackLuster_FunctionLibrary_C.Actor Support Chrome Sound Component // (Static|Public|HasOutParms|BlueprintCallable|BlueprintEvent|BlueprintPure) // @ game+0xdef49c
	void SetChromeAudio(struct AActor* Actor, bool Add, enum class B_Lackluster_ChromeTypes ChromeType, struct UObject* __WorldContext); // Function B_LackLuster_FunctionLibrary.B_LackLuster_FunctionLibrary_C.SetChromeAudio // (Static|Public|BlueprintCallable|BlueprintEvent) // @ game+0xdef49c
	void DisableProxyShadowWPO(struct AActor*& Actor, struct UObject* __WorldContext); // Function B_LackLuster_FunctionLibrary.B_LackLuster_FunctionLibrary_C.DisableProxyShadowWPO // (Static|Public|HasOutParms|HasDefaults|BlueprintCallable|BlueprintEvent) // @ game+0xdef49c
	void ExecuteOwnerTypeFunctionality_PostChrome_Container(struct AActor* Actor, struct FGameplayTagContainer ContainerTags, struct TMap<struct FName, double>& ContainerMaterialScalarParamMap, struct TMap<struct FName, struct FLinearColor>& ContainerMaterialVectorParamMap, struct UObject* __WorldContext); // Function B_LackLuster_FunctionLibrary.B_LackLuster_FunctionLibrary_C.ExecuteOwnerTypeFunctionality_PostChrome_Container // (Static|Public|HasOutParms|HasDefaults|BlueprintCallable|BlueprintEvent) // @ game+0xdef49c
	void ExecuteOwnerTypeFunctionality_PreChrome_Container(struct FGameplayTagContainer ContainerTags, struct TMap<struct FName, double>& ContainerMaterialScalarParamMap, struct TMap<struct FName, struct FLinearColor>& ContainerMaterialVectorParamMap, struct AActor*& Actor, struct UObject* __WorldContext); // Function B_LackLuster_FunctionLibrary.B_LackLuster_FunctionLibrary_C.ExecuteOwnerTypeFunctionality_PreChrome_Container // (Static|Public|HasOutParms|HasDefaults|BlueprintCallable|BlueprintEvent) // @ game+0xdef49c
	void ExecuteOwnerTypeSpecificFunctionality_PostChrome(struct AActor* Actor, enum class B_Lackluster_ActorTypes ActorType, struct FGameplayTagContainer ContainerTags, struct TMap<struct FName, double>& ContainerMaterialScalarParamMap, struct TMap<struct FName, struct FLinearColor>& ContainerMaterialVectorParamMap, struct UObject* __WorldContext); // Function B_LackLuster_FunctionLibrary.B_LackLuster_FunctionLibrary_C.ExecuteOwnerTypeSpecificFunctionality_PostChrome // (Static|Public|HasOutParms|BlueprintCallable|BlueprintEvent) // @ game+0xdef49c
	void ExecuteOwnerTypeSpecificFunctionality_PreChrome(struct AActor* Actor, enum class B_Lackluster_ActorTypes ActorType, struct FGameplayTagContainer ContainerTags, struct TMap<struct FName, double>& ContainerMaterialScalarParamMap, struct TMap<struct FName, struct FLinearColor>& ContainerMaterialVectorParamMap, struct UObject* __WorldContext); // Function B_LackLuster_FunctionLibrary.B_LackLuster_FunctionLibrary_C.ExecuteOwnerTypeSpecificFunctionality_PreChrome // (Static|Public|HasOutParms|BlueprintCallable|BlueprintEvent) // @ game+0xdef49c
	void Apply Chrome to Actor(struct AActor*& Actor, enum class B_Lackluster_ActorTypes& ActorType, enum class B_Lackluster_ChromeTypes& ChromeType, struct TArray<struct FB_Lackluster_ChromeMaterialStruct>& ChromeMaterialStructs, struct TArray<struct FB_Lackluster_OriginalMaterialStruct>& OriginalMaterialStructs, enum class ELacklusterActorType& NativeActorType, enum class ELacklusterChromeType& NativeChromeType, struct TArray<struct FLacklusterMaterialData>& NativeChromeMaterialStructs, struct TArray<struct FLacklusterOriginalMaterialData>& NativeOriginalMaterialStructs, struct TMap<struct FName, double>& ContainerMaterialScalarParamMap, struct TMap<struct FName, struct FLinearColor>& ContainerMaterialVectorParamMap, struct UObject* __WorldContext); // Function B_LackLuster_FunctionLibrary.B_LackLuster_FunctionLibrary_C.Apply Chrome to Actor // (Static|Public|HasOutParms|HasDefaults|BlueprintCallable|BlueprintEvent) // @ game+0xdef49c
	void SetupChromeOnActor(enum class B_Lackluster_ActorTypes& ActorType, enum class B_Lackluster_ChromeTypes& ChromeType, struct TArray<struct FB_Lackluster_ChromeMaterialStruct>& ChromeMaterialStuct, struct TArray<struct FB_Lackluster_OriginalMaterialStruct>& OriginalMaterialStruct, enum class ELacklusterActorType& NativeActorType, enum class ELacklusterChromeType& NativeChromeType, struct TArray<struct FLacklusterMaterialData>& NativeChromeMaterialStruct, struct TArray<struct FLacklusterOriginalMaterialData>& NativeOriginalMaterialStruct, struct AActor* Actor, struct TMap<struct FName, double>& ContainerMaterialScalarParamMap, struct TMap<struct FName, struct FLinearColor>& ContainerMaterialVectorParamMap, struct UObject* __WorldContext); // Function B_LackLuster_FunctionLibrary.B_LackLuster_FunctionLibrary_C.SetupChromeOnActor // (Static|Public|HasOutParms|BlueprintCallable|BlueprintEvent) // @ game+0xdef49c
	void DisableCurieFire(struct AActor* Actor, struct UObject* __WorldContext); // Function B_LackLuster_FunctionLibrary.B_LackLuster_FunctionLibrary_C.DisableCurieFire // (Static|Public|BlueprintCallable|BlueprintEvent) // @ game+0xdef49c
	void Initialize(struct UObject* __WorldContext); // Function B_LackLuster_FunctionLibrary.B_LackLuster_FunctionLibrary_C.Initialize // (Static|Public|HasDefaults|BlueprintCallable|BlueprintEvent) // @ game+0xdef49c
	void PythonApplyChromeToActor(struct AActor* Actor, struct UObject* __WorldContext); // Function B_LackLuster_FunctionLibrary.B_LackLuster_FunctionLibrary_C.PythonApplyChromeToActor // (Static|Public|HasDefaults|BlueprintCallable|BlueprintEvent) // @ game+0xdef49c
	void GetChromeActorType(struct AActor* InActor, struct UObject* __WorldContext, enum class B_Lackluster_ActorTypes& ActorType, enum class B_Lackluster_ChromeTypes& ChromeType); // Function B_LackLuster_FunctionLibrary.B_LackLuster_FunctionLibrary_C.GetChromeActorType // (Static|Public|HasOutParms|BlueprintCallable|BlueprintEvent) // @ game+0xdef49c
	void GetChromeChonkerTires(struct UMeshComponent* MeshCompoenet, struct UObject* __WorldContext, bool& IsChonkers); // Function B_LackLuster_FunctionLibrary.B_LackLuster_FunctionLibrary_C.GetChromeChonkerTires // (Exec|Static|Private|HasOutParms|BlueprintCallable|BlueprintEvent|BlueprintPure) // @ game+0xdef49c
	void GetChromeTieredChestMaterial(struct AActor* InActor, struct UObject* __WorldContext, struct UMaterialInstance*& MaterialInstance); // Function B_LackLuster_FunctionLibrary.B_LackLuster_FunctionLibrary_C.GetChromeTieredChestMaterial // (Exec|Static|Private|HasOutParms|HasDefaults|BlueprintCallable|BlueprintEvent|BlueprintPure) // @ game+0xdef49c
	void GetChromeSoundComponent(struct AActor* Actor, bool CreateComponentIfNotFound, struct UObject* __WorldContext, struct UChromeSoundComponent_C*& Results); // Function B_LackLuster_FunctionLibrary.B_LackLuster_FunctionLibrary_C.GetChromeSoundComponent // (Static|Public|HasOutParms|BlueprintCallable|BlueprintEvent|BlueprintPure) // @ game+0xdef49c
	void GetChromeVisualComponent(struct AActor* Actor, bool CreateComponentIfNotFound, struct UObject* __WorldContext, struct UB_Lackluster_ApplyChrome_C*& Result); // Function B_LackLuster_FunctionLibrary.B_LackLuster_FunctionLibrary_C.GetChromeVisualComponent // (Static|Public|HasOutParms|BlueprintCallable|BlueprintEvent) // @ game+0xdef49c
	void SetChromeMaterials(struct TArray<struct FB_Lackluster_ChromeMaterialStruct>& Array, enum class B_Lackluster_ChromeTypes ChromeType, struct UObject* __WorldContext); // Function B_LackLuster_FunctionLibrary.B_LackLuster_FunctionLibrary_C.SetChromeMaterials // (Static|Public|HasOutParms|HasDefaults|BlueprintCallable|BlueprintEvent) // @ game+0xdef49c
	void GetChromeMaterialOverride(bool IsMasked, enum class B_Lackluster_ActorTypes ActorType, struct AActor* Actor, enum class B_Lackluster_ChromeTypes ChromeType, int32_t MaterialIndex, struct UObject* __WorldContext, struct UMaterialInterface*& ChromeMaterial, bool& IsImpostorMaterial_out, struct UMaterialInstanceDynamic*& ImpostorMaterial_out); // Function B_LackLuster_FunctionLibrary.B_LackLuster_FunctionLibrary_C.GetChromeMaterialOverride // (Static|Private|HasOutParms|HasDefaults|BlueprintCallable|BlueprintEvent|BlueprintPure) // @ game+0xdef49c
	void Is Chrome Parent Already Applied(struct UMaterialInstance* Material Interface, struct UObject* __WorldContext, bool& Result); // Function B_LackLuster_FunctionLibrary.B_LackLuster_FunctionLibrary_C.Is Chrome Parent Already Applied // (Static|Private|HasOutParms|BlueprintCallable|BlueprintEvent|BlueprintPure) // @ game+0xdef49c
	struct FName FindSetParameterName(enum class B_Lackluster_TextureGroup TextureGroup, struct UObject* __WorldContext); // Function B_LackLuster_FunctionLibrary.B_LackLuster_FunctionLibrary_C.FindSetParameterName // (Static|Private|HasOutParms|BlueprintCallable|BlueprintEvent|BlueprintPure) // @ game+0xdef49c
	struct TArray<struct FB_Lackluster_Texture_Set> FindGetSetParameters(bool IsMaskedMaterial, enum class B_Lackluster_ActorTypes ActorType, struct UMeshComponent* MeshComponent, struct UObject* __WorldContext); // Function B_LackLuster_FunctionLibrary.B_LackLuster_FunctionLibrary_C.FindGetSetParameters // (Static|Private|HasOutParms|HasDefaults|BlueprintCallable|BlueprintEvent|BlueprintPure) // @ game+0xdef49c
	bool IsMaskedBlendMode(struct UMaterialInterface* MaterialInterface, struct UObject* __WorldContext); // Function B_LackLuster_FunctionLibrary.B_LackLuster_FunctionLibrary_C.IsMaskedBlendMode // (Static|Private|HasOutParms|BlueprintCallable|BlueprintEvent|BlueprintPure) // @ game+0xdef49c
	bool Should Ignore Material(struct UMaterialInterface* MaterialInterface, struct UObject* __WorldContext); // Function B_LackLuster_FunctionLibrary.B_LackLuster_FunctionLibrary_C.Should Ignore Material // (Static|Private|HasOutParms|HasDefaults|BlueprintCallable|BlueprintEvent|BlueprintPure) // @ game+0xdef49c
	void FindTexturesFromComponents(enum class B_Lackluster_ActorTypes ActorType, struct AActor* Actor, struct UObject* __WorldContext, struct TArray<struct FB_Lackluster_ChromeMaterialStruct>& ChromeMaterialStruct, struct TArray<struct FB_Lackluster_OriginalMaterialStruct>& OriginalMaterialStruct); // Function B_LackLuster_FunctionLibrary.B_LackLuster_FunctionLibrary_C.FindTexturesFromComponents // (Static|Private|HasOutParms|HasDefaults|BlueprintCallable|BlueprintEvent) // @ game+0xdef49c
	bool ExcludeFromChroming(struct USceneComponent* SceneComponent, struct UObject* __WorldContext); // Function B_LackLuster_FunctionLibrary.B_LackLuster_FunctionLibrary_C.ExcludeFromChroming // (Static|Private|HasOutParms|BlueprintCallable|BlueprintEvent|BlueprintPure) // @ game+0xdef49c
	void CastToParentClasses(struct AActor* ActorObjectRef, struct UObject* __WorldContext, bool& Found, enum class B_Lackluster_ActorTypes& FoundActorType); // Function B_LackLuster_FunctionLibrary.B_LackLuster_FunctionLibrary_C.CastToParentClasses // (Static|Private|HasOutParms|BlueprintCallable|BlueprintEvent) // @ game+0xdef49c
	void CastToSpecificClasses(struct AActor* ActorObjectRef, enum class B_Lackluster_ChromeTypes ChromeType, struct UObject* __WorldContext, bool& Found, enum class B_Lackluster_ActorTypes& ActorType, enum class B_Lackluster_ChromeTypes& ChromeTypeOut); // Function B_LackLuster_FunctionLibrary.B_LackLuster_FunctionLibrary_C.CastToSpecificClasses // (Static|Private|HasOutParms|HasDefaults|BlueprintCallable|BlueprintEvent) // @ game+0xdef49c
	void ApplyChromeMaterial(struct AActor* Actor, struct TArray<struct FB_Lackluster_ChromeMaterialStruct>& ChromeMaterialStructIn, struct TArray<struct FB_Lackluster_OriginalMaterialStruct>& OriginalMaterialStructIn, enum class B_Lackluster_ChromeTypes ChromeType, enum class B_Lackluster_ActorTypes OverrideActorType, struct UObject* __WorldContext); // Function B_LackLuster_FunctionLibrary.B_LackLuster_FunctionLibrary_C.ApplyChromeMaterial // (Static|Public|HasOutParms|HasDefaults|BlueprintCallable|BlueprintEvent) // @ game+0xdef49c
};

