// BlueprintGeneratedClass CampsiteFunctionLibrary.CampsiteFunctionLibrary_C
// Size: 0x28 (Inherited: 0x28)
struct UCampsiteFunctionLibrary_C : UBlueprintFunctionLibrary {

	void FilterPlayerStatesForActivePlayers(struct TArray<struct AFortPlayerStateAthena*>& InPlayerStates, struct UObject* __WorldContext, struct TArray<struct AFortPlayerStateAthena*>& FilteredPlayerStates); // Function CampsiteFunctionLibrary.CampsiteFunctionLibrary_C.FilterPlayerStatesForActivePlayers // (Static|Private|HasOutParms|HasDefaults|BlueprintCallable|BlueprintEvent) // @ game+0xdef49c
	void TentBouncePlayerOnHit(struct AFortPlayerPawn* HitPlayerPawn, struct AActor* Tent, struct FGameplayTag Bounce GC, struct FVector Hit Location, struct FVector Hit Normal, struct TArray<struct AFortPlayerPawn*>& Recently Launched, struct UObject* __WorldContext, struct AFortPlayerPawn*& Launched Pawn); // Function CampsiteFunctionLibrary.CampsiteFunctionLibrary_C.TentBouncePlayerOnHit // (Static|Public|HasOutParms|HasDefaults|BlueprintCallable|BlueprintEvent) // @ game+0xdef49c
	void RandomRotationOnSurfaceNormal(struct FVector& inputNormal, struct UObject* __WorldContext, struct FRotator& Rotation); // Function CampsiteFunctionLibrary.CampsiteFunctionLibrary_C.RandomRotationOnSurfaceNormal // (Static|Public|HasOutParms|BlueprintCallable|BlueprintEvent|BlueprintPure) // @ game+0xdef49c
	void GetNearestCampsite(struct TArray<struct ABGA_Campsite_C*>& Campsites, struct FVector targetLoc, struct UObject* __WorldContext, struct ABGA_Campsite_C*& nearest camp); // Function CampsiteFunctionLibrary.CampsiteFunctionLibrary_C.GetNearestCampsite // (Static|Public|HasOutParms|BlueprintCallable|BlueprintEvent|BlueprintPure) // @ game+0xdef49c
	struct FRotator RotatorFacingTargetAlongNormal(struct FVector& Start, struct FVector& Target, struct FVector RotationAxis, double Xdirection, struct UObject* __WorldContext); // Function CampsiteFunctionLibrary.CampsiteFunctionLibrary_C.RotatorFacingTargetAlongNormal // (Static|Public|HasOutParms|BlueprintCallable|BlueprintEvent|BlueprintPure) // @ game+0xdef49c
	void Spawn And Establish New Campsite(struct AFortPlayerStateAthena* Player State Athena, struct FTransform& Transform, struct AActor* SupportingActor, struct FFortItemEntry Instigating Item, struct UObject* __WorldContext, struct ABGA_Campsite_C*& AsBGA Campsite); // Function CampsiteFunctionLibrary.CampsiteFunctionLibrary_C.Spawn And Establish New Campsite // (Static|Public|HasOutParms|BlueprintCallable|BlueprintEvent) // @ game+0xdef49c
	void Trajectory Placement Preview Campsite(struct TScriptInterface<IFortTrajectoryAbilityInterface> Target, enum class Enum_Campsite_Improvements ImprovementType, struct ABP_ProjectileTrajectory_C* TrajectoryIndicator, struct ABP_ProjectileTrajectory_C* TrajectoryIndicatorRed, struct APawn* ThrowingPlayerActor, bool isTrajHidden?, struct UObject* Class, double MinDistanceFromObstacles, struct UObject* __WorldContext, struct ABGA_Campsite_C*& target campsite, bool& valid?); // Function CampsiteFunctionLibrary.CampsiteFunctionLibrary_C.Trajectory Placement Preview Campsite // (Static|Public|HasOutParms|HasDefaults|BlueprintCallable|BlueprintEvent) // @ game+0xdef49c
	void BestCampsiteForNewImprovement(enum class Enum_Campsite_Improvements ImprovementType, struct TArray<struct ABGA_Campsite_C*>& NearbyCampsites, struct FVector QueryLocation, struct UObject* __WorldContext, struct ABGA_Campsite_C*& BestCampsite); // Function CampsiteFunctionLibrary.CampsiteFunctionLibrary_C.BestCampsiteForNewImprovement // (Static|Public|HasOutParms|HasDefaults|BlueprintCallable|BlueprintEvent) // @ game+0xdef49c
	void Surface Supports Campsite Deployment?(struct FHitResult& Hit, double MinDistanceFromObstacles, struct AActor* InstigatingActor, struct FRotator ProjRotation, struct UObject* __WorldContext, bool& validSurface); // Function CampsiteFunctionLibrary.CampsiteFunctionLibrary_C.Surface Supports Campsite Deployment? // (Static|Public|HasOutParms|HasDefaults|BlueprintCallable|BlueprintEvent) // @ game+0xdef49c
	void Raycast Improvement Positioning(struct FVector Desired Location, struct TArray<struct AActor*>& ActorsToIgnore, struct UObject* __WorldContext, struct FHitResult& Hit); // Function CampsiteFunctionLibrary.CampsiteFunctionLibrary_C.Raycast Improvement Positioning // (Static|Public|HasOutParms|HasDefaults|BlueprintCallable|BlueprintEvent) // @ game+0xdef49c
	void Best Squadmate And Campsite To Add New Tent(struct TArray<struct ABGA_Campsite_C*>& Campsites to Search, struct AFortPlayerStateAthena* Reference Player State, struct FVector Reference Location, struct UObject* __WorldContext, struct ABGA_Campsite_C*& Campsite, struct APlayerState*& Player); // Function CampsiteFunctionLibrary.CampsiteFunctionLibrary_C.Best Squadmate And Campsite To Add New Tent // (Static|Public|HasOutParms|HasDefaults|BlueprintCallable|BlueprintEvent) // @ game+0xdef49c
	void Get Nearby Campsites(struct AFortPlayerStateAthena* ReferencePlayerState, struct FVector InquiryLocation, struct TArray<struct AActor*>& ActorsToIgnore, struct UObject* __WorldContext, struct TArray<struct ABGA_Campsite_C*>& FriendlyCampsites, struct TArray<struct ABGA_Campsite_C*>& EnemyCampsites); // Function CampsiteFunctionLibrary.CampsiteFunctionLibrary_C.Get Nearby Campsites // (Static|Public|HasOutParms|HasDefaults|BlueprintCallable|BlueprintEvent) // @ game+0xdef49c
};

