// BlueprintGeneratedClass LaunchpadFunctionLibrary.LaunchpadFunctionLibrary_C
// Size: 0x28 (Inherited: 0x28)
struct ULaunchpadFunctionLibrary_C : UBlueprintFunctionLibrary {

	void Launchpad Terrain Otherside Check(struct AActor* Self Ref, struct FHitResult Stopped  Hit Result, struct FVector Spawn Location Bottom Center, bool Debug, struct UObject* __WorldContext, bool& Spawning on Otherside); // Function LaunchpadFunctionLibrary.LaunchpadFunctionLibrary_C.Launchpad Terrain Otherside Check // (Static|Public|HasOutParms|HasDefaults|BlueprintCallable|BlueprintEvent|BlueprintPure) // @ game+0xdef49c
	void Launchpad Ramp Float Check(struct AActor* Self Ref, struct FVector Bottom Center of Cell, bool Debug, struct UObject* __WorldContext, bool& Would Be Floating); // Function LaunchpadFunctionLibrary.LaunchpadFunctionLibrary_C.Launchpad Ramp Float Check // (Static|Public|HasOutParms|HasDefaults|BlueprintCallable|BlueprintEvent|BlueprintPure) // @ game+0xdef49c
	void Launchpad Ramp Trace Check(struct UObject* Actor Self Reference, struct FVector Location, struct FVector Grid Center Correction Offset, float Radius, enum class EDrawDebugTrace DrawDebugType, struct FLinearColor TraceColor, struct FLinearColor TraceHitColor, float DrawTime, struct UObject* __WorldContext, bool& Ramp Rules Apply, struct AActor*& Ramp Actor); // Function LaunchpadFunctionLibrary.LaunchpadFunctionLibrary_C.Launchpad Ramp Trace Check // (Static|Public|HasOutParms|HasDefaults|BlueprintCallable|BlueprintEvent) // @ game+0xdef49c
	void Launchpad Placement Multi Trace(struct AActor* Self Actor, struct FVector Center Position, struct FVector Center Position Offset, struct FVector Trace Top, struct FVector Trace Bottom, struct TArray<struct AActor*>& ActorsToIgnore, enum class EDrawDebugTrace Draw Debug Type, struct FLinearColor TraceColor, struct FLinearColor TraceHitColor, double Draw Time, struct UObject* __WorldContext, struct TArray<struct FHitResult>& OutHits); // Function LaunchpadFunctionLibrary.LaunchpadFunctionLibrary_C.Launchpad Placement Multi Trace // (Static|Public|HasOutParms|HasDefaults|BlueprintCallable|BlueprintEvent) // @ game+0xdef49c
	void Launchpad Round to Nearest Angle(int32_t Angle, struct UObject* __WorldContext, int32_t& Rounded Angle); // Function LaunchpadFunctionLibrary.LaunchpadFunctionLibrary_C.Launchpad Round to Nearest Angle // (Static|Public|HasOutParms|BlueprintCallable|BlueprintEvent|BlueprintPure) // @ game+0xdef49c
	void Launchpad Ramp Handling(struct AActor* Ramp Actor, struct FVector Target Location, struct UObject* Self Reference, struct FVector Grid Snapped Position, struct FVector Grid Snap Pos Offset, bool Debug, struct UObject* __WorldContext, struct FVector& New Grid Snapped Position); // Function LaunchpadFunctionLibrary.LaunchpadFunctionLibrary_C.Launchpad Ramp Handling // (Static|Public|HasOutParms|HasDefaults|BlueprintCallable|BlueprintEvent) // @ game+0xdef49c
	void Launchpad Affiliation Check(struct AActor* Self Actor, struct AFortPlayerController* Instigator Controller, struct FVector Center Cell Location, enum class Enum_LaunchpadSpawnVariants Check Size, bool Debug, struct UObject* __WorldContext, bool& Is Hostile); // Function LaunchpadFunctionLibrary.LaunchpadFunctionLibrary_C.Launchpad Affiliation Check // (Static|Public|HasOutParms|HasDefaults|BlueprintCallable|BlueprintEvent) // @ game+0xdef49c
	void Launchpad Ramp Check(struct FHitResult Stopped Hit Result, bool Debug, struct UObject* __WorldContext, bool& Ramp Rules Apply, struct AActor*& Ramp Actor); // Function LaunchpadFunctionLibrary.LaunchpadFunctionLibrary_C.Launchpad Ramp Check // (Static|Public|HasOutParms|HasDefaults|BlueprintCallable|BlueprintEvent|BlueprintPure) // @ game+0xdef49c
	void Launchpad Ramp Underside Check(struct AActor* Ramp Actor, struct FVector Ramp Impact Location, struct UObject* __WorldContext, bool& Is Underside); // Function LaunchpadFunctionLibrary.LaunchpadFunctionLibrary_C.Launchpad Ramp Underside Check // (Static|Public|HasOutParms|HasDefaults|BlueprintCallable|BlueprintEvent|BlueprintPure) // @ game+0xdef49c
	void Launchpad Floor Check(struct TArray<struct FHitResult>& Hit Results, bool Debug On, struct UObject* __WorldContext, bool& Floor Found, struct AActor*& Detected Floor Actor); // Function LaunchpadFunctionLibrary.LaunchpadFunctionLibrary_C.Launchpad Floor Check // (Static|Public|HasOutParms|HasDefaults|BlueprintCallable|BlueprintEvent|BlueprintPure) // @ game+0xdef49c
	void Launchpad Terrain Check(struct UObject* Self Ref, struct TArray<struct FHitResult>& Hit Results, double Distance Threshold, bool Debug, struct UObject* __WorldContext, bool& Terrain Found); // Function LaunchpadFunctionLibrary.LaunchpadFunctionLibrary_C.Launchpad Terrain Check // (Static|Public|HasOutParms|HasDefaults|BlueprintCallable|BlueprintEvent) // @ game+0xdef49c
};

